//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.dailyts {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblDT_CO_CODE;
	protected global::System.Web.UI.WebControls.Label lblDT_STAFF_CODE;
	protected global::System.Web.UI.WebControls.Label lblDT_WORK_DATE;
	protected global::System.Web.UI.WebControls.Label lblDT_LINE_NO;
	protected global::System.Web.UI.WebControls.Label lblDT_APP_CODE;
	protected global::System.Web.UI.WebControls.Label lblDT_JOB_CODE;
	protected global::System.Web.UI.WebControls.Label lblDT_SER_CODE;
	protected global::System.Web.UI.WebControls.Label lblDT_NOR_HOUR;
	protected global::System.Web.UI.WebControls.Label lblDT_OVER_HOUR;
	protected global::System.Web.UI.WebControls.Label lblDT_TYPE;
	protected global::System.Web.UI.WebControls.Label lblDT_PERIOD;
	protected global::System.Web.UI.WebControls.Label lblDT_SUBMIT;
	protected global::System.Web.UI.WebControls.Label lblDT_UPDATE;
	protected global::System.Web.UI.WebControls.Label lblDT_RAMNO;
	protected global::System.Web.UI.WebControls.Label lblDT_UPDATE_DATE;

    }
}
