//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.position {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtPOS_CO_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_DESC;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_FEE_LEV1;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_FEE_LEV2;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_FEE_LEV3;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_RATE_OUT;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_RATE_DAILY;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_RATE_MON;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_RATE_OT;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_MON_TOTAL;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_MON_UTILIST;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_MON_REV;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_SAL_FROM;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_SAL_TO;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_DALIY_COST;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_MON_COST;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_CLASS;
		protected global::System.Web.UI.WebControls.TextBox txtPOS_PLAN;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
