//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.position {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblPOS_CO_CODE;
	protected global::System.Web.UI.WebControls.Label lblPOS_CODE;
	protected global::System.Web.UI.WebControls.Label lblPOS_DESC;
	protected global::System.Web.UI.WebControls.Label lblPOS_FEE_LEV1;
	protected global::System.Web.UI.WebControls.Label lblPOS_FEE_LEV2;
	protected global::System.Web.UI.WebControls.Label lblPOS_FEE_LEV3;
	protected global::System.Web.UI.WebControls.Label lblPOS_RATE_OUT;
	protected global::System.Web.UI.WebControls.Label lblPOS_RATE_DAILY;
	protected global::System.Web.UI.WebControls.Label lblPOS_RATE_MON;
	protected global::System.Web.UI.WebControls.Label lblPOS_RATE_OT;
	protected global::System.Web.UI.WebControls.Label lblPOS_MON_TOTAL;
	protected global::System.Web.UI.WebControls.Label lblPOS_MON_UTILIST;
	protected global::System.Web.UI.WebControls.Label lblPOS_MON_REV;
	protected global::System.Web.UI.WebControls.Label lblPOS_SAL_FROM;
	protected global::System.Web.UI.WebControls.Label lblPOS_SAL_TO;
	protected global::System.Web.UI.WebControls.Label lblPOS_DALIY_COST;
	protected global::System.Web.UI.WebControls.Label lblPOS_MON_COST;
	protected global::System.Web.UI.WebControls.Label lblPOS_CLASS;
	protected global::System.Web.UI.WebControls.Label lblPOS_PLAN;

    }
}
