//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.emp_day_tem {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtED_JS_1;
		protected global::System.Web.UI.WebControls.TextBox txtED_JS_2;
		protected global::System.Web.UI.WebControls.TextBox txtED_JS_3;
		protected global::System.Web.UI.WebControls.TextBox txtED_JS_4;
		protected global::System.Web.UI.WebControls.TextBox txtED_JS_5;
		protected global::System.Web.UI.WebControls.TextBox txtED_JS_6;
		protected global::System.Web.UI.WebControls.TextBox txtED_JS_7;
		protected global::System.Web.UI.WebControls.TextBox txtED_JS_8;
		protected global::System.Web.UI.WebControls.TextBox txtED_JS_9;
		protected global::System.Web.UI.WebControls.TextBox txtED_JS_10;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
