//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.employee {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblEMP_CO_CODE;
	protected global::System.Web.UI.WebControls.Label lblEMP_CODE;
	protected global::System.Web.UI.WebControls.Label lblEMP_NAME;
	protected global::System.Web.UI.WebControls.Label lblEMP_POS_CODE;
	protected global::System.Web.UI.WebControls.Label lblEMP_DEP_CODE;
	protected global::System.Web.UI.WebControls.Label lblEMP_INITIAL;
	protected global::System.Web.UI.WebControls.Label lblEMP_OFFICE;
	protected global::System.Web.UI.WebControls.Label lblEMP_CHNAME;
	protected global::System.Web.UI.WebControls.Label lblEMP_SPE;
	protected global::System.Web.UI.WebControls.Label lblEMP_CRE_DATE;
	protected global::System.Web.UI.WebControls.Label lblEMP_DEL;

    }
}
