//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.outstanding_temp {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblNUM;
	protected global::System.Web.UI.WebControls.Label lblOUT_OFF_CODE;
	protected global::System.Web.UI.WebControls.Label lblOUT_OFF_NAME;
	protected global::System.Web.UI.WebControls.Label lblOUT_EMP_CODE;
	protected global::System.Web.UI.WebControls.Label lblOUT_EMP_NAME;
	protected global::System.Web.UI.WebControls.Label lblOUT_DAY;
	protected global::System.Web.UI.WebControls.Label lblOUT_POS_CLASS;
	protected global::System.Web.UI.WebControls.Label lblOUT_POS_CODE;
	protected global::System.Web.UI.WebControls.Label lblOUT_UPDATE_DATE;

    }
}
