//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.incomts {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtIST_CO_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtIST_OFFCIE_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtIST_WORK_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtIST_USER_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtIST_USER_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtIST_INPUT_OK;
		protected global::System.Web.UI.WebControls.TextBox txtIST_APP;
		protected global::System.Web.UI.WebControls.TextBox txtIST_NOR_HR;
		protected global::System.Web.UI.WebControls.TextBox txtIST_OT_HR;
		protected global::System.Web.UI.WebControls.TextBox txtIST_PERIOD;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
