//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.incomts {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblIST_CO_CODE;
	protected global::System.Web.UI.WebControls.Label lblIST_OFFCIE_CODE;
	protected global::System.Web.UI.WebControls.Label lblIST_WORK_DATE;
	protected global::System.Web.UI.WebControls.Label lblIST_USER_CODE;
	protected global::System.Web.UI.WebControls.Label lblIST_USER_NAME;
	protected global::System.Web.UI.WebControls.Label lblIST_INPUT_OK;
	protected global::System.Web.UI.WebControls.Label lblIST_APP;
	protected global::System.Web.UI.WebControls.Label lblIST_NOR_HR;
	protected global::System.Web.UI.WebControls.Label lblIST_OT_HR;
	protected global::System.Web.UI.WebControls.Label lblIST_PERIOD;

    }
}
