//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.job {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtJOB_CO_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_CON;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_OPEN_BAL_HOUR;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_YTD_HOUR;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_OPEN_BAL_AMT;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_YTD_AMT;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_REC;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_OS_BAL;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_BUD_HOUR;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_CO_ORD;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_ADMIN;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_DESIGN;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_LEV1;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_LEV2;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_LEV3;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_CHARGE_OUT;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_DAILY;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_MON;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_PERIOD;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_PERIOD_VAL;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_AUTH;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_OFF_INCHG_AD;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_OFF_INCHG_DES;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_AUTH_1;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_AUTH_2;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_AUTH_3;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_AUTH_4;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_AUTH_5;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_INDEX;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_NAME_S;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_NAME_T;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
