//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.job {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblJOB_CO_CODE;
	protected global::System.Web.UI.WebControls.Label lblJOB_CODE;
	protected global::System.Web.UI.WebControls.Label lblJOB_NAME;
	protected global::System.Web.UI.WebControls.Label lblJOB_CON;
	protected global::System.Web.UI.WebControls.Label lblJOB_OPEN_BAL_HOUR;
	protected global::System.Web.UI.WebControls.Label lblJOB_YTD_HOUR;
	protected global::System.Web.UI.WebControls.Label lblJOB_OPEN_BAL_AMT;
	protected global::System.Web.UI.WebControls.Label lblJOB_YTD_AMT;
	protected global::System.Web.UI.WebControls.Label lblJOB_REC;
	protected global::System.Web.UI.WebControls.Label lblJOB_OS_BAL;
	protected global::System.Web.UI.WebControls.Label lblJOB_BUD_HOUR;
	protected global::System.Web.UI.WebControls.Label lblJOB_CO_ORD;
	protected global::System.Web.UI.WebControls.Label lblJOB_ADMIN;
	protected global::System.Web.UI.WebControls.Label lblJOB_DESIGN;
	protected global::System.Web.UI.WebControls.Label lblJOB_LEV1;
	protected global::System.Web.UI.WebControls.Label lblJOB_LEV2;
	protected global::System.Web.UI.WebControls.Label lblJOB_LEV3;
	protected global::System.Web.UI.WebControls.Label lblJOB_CHARGE_OUT;
	protected global::System.Web.UI.WebControls.Label lblJOB_DAILY;
	protected global::System.Web.UI.WebControls.Label lblJOB_MON;
	protected global::System.Web.UI.WebControls.Label lblJOB_PERIOD;
	protected global::System.Web.UI.WebControls.Label lblJOB_PERIOD_VAL;
	protected global::System.Web.UI.WebControls.Label lblJOB_AUTH;
	protected global::System.Web.UI.WebControls.Label lblJOB_OFF_INCHG_AD;
	protected global::System.Web.UI.WebControls.Label lblJOB_OFF_INCHG_DES;
	protected global::System.Web.UI.WebControls.Label lblJOB_AUTH_1;
	protected global::System.Web.UI.WebControls.Label lblJOB_AUTH_2;
	protected global::System.Web.UI.WebControls.Label lblJOB_AUTH_3;
	protected global::System.Web.UI.WebControls.Label lblJOB_AUTH_4;
	protected global::System.Web.UI.WebControls.Label lblJOB_AUTH_5;
	protected global::System.Web.UI.WebControls.Label lblJOB_INDEX;
	protected global::System.Web.UI.WebControls.Label lblJOB_NAME_S;
	protected global::System.Web.UI.WebControls.Label lblJOB_NAME_T;

    }
}
