//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.company {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCO_CODE;
	protected global::System.Web.UI.WebControls.Label lblCO_SCR_NAME;
	protected global::System.Web.UI.WebControls.Label lblCO_RPT_NAME;
	protected global::System.Web.UI.WebControls.Label lblCO_LB_DATE;
	protected global::System.Web.UI.WebControls.Label lblCO_LE_DATE;
	protected global::System.Web.UI.WebControls.Label lblCO_CB_DATE;
	protected global::System.Web.UI.WebControls.Label lblCO_CE_DATE;
	protected global::System.Web.UI.WebControls.Label lblCO_CURR;
	protected global::System.Web.UI.WebControls.Label lblCO_PERIOD_FROM;
	protected global::System.Web.UI.WebControls.Label lblCO_PERIOD_TO;

    }
}
