//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1873
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Acct {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Acct.AcctDataSoap")]
    public interface AcctDataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string CustomerList(string companyCode, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string UpdateCustomerStatus(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Demo_Customer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbExrateDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbCustomer))]
        Test.Acct.tbCustomer Demo_Customer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SupplierList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbExrateDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbCustomer))]
        string SupplierList(string companyCode, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSupplierStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbExrateDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbCustomer))]
        string UpdateSupplierStatus(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExRateDtList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbExrateDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbCustomer))]
        string ExRateDtList(string companyCode, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateExRateDtStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbExrateDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbCustomer))]
        string UpdateExRateDtStatus(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Demo_ExchangeRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbExrateDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbCustomer))]
        Test.Acct.tbExrateDetail Demo_ExchangeRate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustCrLmtList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbExrateDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbCustomer))]
        string CustCrLmtList(string companyCode, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustCrLmtStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbExrateDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseTableOftbCustomer))]
        string UpdateCustCrLmtStatus(string xml);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tbCustomer : BaseTableOftbCustomer {
        
        private string companyCodeField;
        
        private string cltcodeField;
        
        private string cltnameField;
        
        private string teamCodeField;
        
        private string masteracctField;
        
        private string addr1Field;
        
        private string addr2Field;
        
        private string addr3Field;
        
        private string addr4Field;
        
        private string addr5Field;
        
        private string citycodeField;
        
        private string countrycodeField;
        
        private string postcodeField;
        
        private string billAddr1Field;
        
        private string billAddr2Field;
        
        private string billAddr3Field;
        
        private string billAddr4Field;
        
        private string billAddr5Field;
        
        private string billPostalField;
        
        private string billCityField;
        
        private string billCountryField;
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string fax1Field;
        
        private string fax2Field;
        
        private string title1Field;
        
        private string contact1Field;
        
        private string title2Field;
        
        private string contact2Field;
        
        private string currcodeField;
        
        private string payMethodField;
        
        private string payTermTypeField;
        
        private string payTermDaysField;
        
        private string controllerField;
        
        private string bankGLAcctField;
        
        private string ctrlGLAcctField;
        
        private string sttGroupField;
        
        private int sttCopiesField;
        
        private string remarksField;
        
        private decimal prftupField;
        
        private decimal prftdownField;
        
        private string categoryField;
        
        private string email1Field;
        
        private string email2Field;
        
        private string exrateCodeField;
        
        private string acctStatusField;
        
        private string statementAddr1Field;
        
        private string statementAddr2Field;
        
        private string statementAddr3Field;
        
        private string statementAddr4Field;
        
        private string statementAddr5Field;
        
        private string branchCodeField;
        
        private string internalField;
        
        private string gemsCodeField;
        
        private string gemsCustCodeField;
        
        private string salespersonField;
        
        private decimal depositField;
        
        private string salesGroupField;
        
        private System.DateTime createonField;
        
        private string createbyField;
        
        private System.DateTime updateonField;
        
        private string updatebyField;
        
        private System.DateTime syncOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Cltcode {
            get {
                return this.cltcodeField;
            }
            set {
                this.cltcodeField = value;
                this.RaisePropertyChanged("Cltcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Cltname {
            get {
                return this.cltnameField;
            }
            set {
                this.cltnameField = value;
                this.RaisePropertyChanged("Cltname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TeamCode {
            get {
                return this.teamCodeField;
            }
            set {
                this.teamCodeField = value;
                this.RaisePropertyChanged("TeamCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Masteracct {
            get {
                return this.masteracctField;
            }
            set {
                this.masteracctField = value;
                this.RaisePropertyChanged("Masteracct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Addr1 {
            get {
                return this.addr1Field;
            }
            set {
                this.addr1Field = value;
                this.RaisePropertyChanged("Addr1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Addr2 {
            get {
                return this.addr2Field;
            }
            set {
                this.addr2Field = value;
                this.RaisePropertyChanged("Addr2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Addr3 {
            get {
                return this.addr3Field;
            }
            set {
                this.addr3Field = value;
                this.RaisePropertyChanged("Addr3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Addr4 {
            get {
                return this.addr4Field;
            }
            set {
                this.addr4Field = value;
                this.RaisePropertyChanged("Addr4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Addr5 {
            get {
                return this.addr5Field;
            }
            set {
                this.addr5Field = value;
                this.RaisePropertyChanged("Addr5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Citycode {
            get {
                return this.citycodeField;
            }
            set {
                this.citycodeField = value;
                this.RaisePropertyChanged("Citycode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Countrycode {
            get {
                return this.countrycodeField;
            }
            set {
                this.countrycodeField = value;
                this.RaisePropertyChanged("Countrycode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("Postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string BillAddr1 {
            get {
                return this.billAddr1Field;
            }
            set {
                this.billAddr1Field = value;
                this.RaisePropertyChanged("BillAddr1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BillAddr2 {
            get {
                return this.billAddr2Field;
            }
            set {
                this.billAddr2Field = value;
                this.RaisePropertyChanged("BillAddr2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BillAddr3 {
            get {
                return this.billAddr3Field;
            }
            set {
                this.billAddr3Field = value;
                this.RaisePropertyChanged("BillAddr3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string BillAddr4 {
            get {
                return this.billAddr4Field;
            }
            set {
                this.billAddr4Field = value;
                this.RaisePropertyChanged("BillAddr4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string BillAddr5 {
            get {
                return this.billAddr5Field;
            }
            set {
                this.billAddr5Field = value;
                this.RaisePropertyChanged("BillAddr5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string BillPostal {
            get {
                return this.billPostalField;
            }
            set {
                this.billPostalField = value;
                this.RaisePropertyChanged("BillPostal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string BillCity {
            get {
                return this.billCityField;
            }
            set {
                this.billCityField = value;
                this.RaisePropertyChanged("BillCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string BillCountry {
            get {
                return this.billCountryField;
            }
            set {
                this.billCountryField = value;
                this.RaisePropertyChanged("BillCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
                this.RaisePropertyChanged("Phone1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
                this.RaisePropertyChanged("Phone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Fax1 {
            get {
                return this.fax1Field;
            }
            set {
                this.fax1Field = value;
                this.RaisePropertyChanged("Fax1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Fax2 {
            get {
                return this.fax2Field;
            }
            set {
                this.fax2Field = value;
                this.RaisePropertyChanged("Fax2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Title1 {
            get {
                return this.title1Field;
            }
            set {
                this.title1Field = value;
                this.RaisePropertyChanged("Title1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Contact1 {
            get {
                return this.contact1Field;
            }
            set {
                this.contact1Field = value;
                this.RaisePropertyChanged("Contact1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Title2 {
            get {
                return this.title2Field;
            }
            set {
                this.title2Field = value;
                this.RaisePropertyChanged("Title2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Contact2 {
            get {
                return this.contact2Field;
            }
            set {
                this.contact2Field = value;
                this.RaisePropertyChanged("Contact2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Currcode {
            get {
                return this.currcodeField;
            }
            set {
                this.currcodeField = value;
                this.RaisePropertyChanged("Currcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string PayMethod {
            get {
                return this.payMethodField;
            }
            set {
                this.payMethodField = value;
                this.RaisePropertyChanged("PayMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string PayTermType {
            get {
                return this.payTermTypeField;
            }
            set {
                this.payTermTypeField = value;
                this.RaisePropertyChanged("PayTermType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string PayTermDays {
            get {
                return this.payTermDaysField;
            }
            set {
                this.payTermDaysField = value;
                this.RaisePropertyChanged("PayTermDays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Controller {
            get {
                return this.controllerField;
            }
            set {
                this.controllerField = value;
                this.RaisePropertyChanged("Controller");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string BankGLAcct {
            get {
                return this.bankGLAcctField;
            }
            set {
                this.bankGLAcctField = value;
                this.RaisePropertyChanged("BankGLAcct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string CtrlGLAcct {
            get {
                return this.ctrlGLAcctField;
            }
            set {
                this.ctrlGLAcctField = value;
                this.RaisePropertyChanged("CtrlGLAcct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string SttGroup {
            get {
                return this.sttGroupField;
            }
            set {
                this.sttGroupField = value;
                this.RaisePropertyChanged("SttGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public int SttCopies {
            get {
                return this.sttCopiesField;
            }
            set {
                this.sttCopiesField = value;
                this.RaisePropertyChanged("SttCopies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
                this.RaisePropertyChanged("Remarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public decimal Prftup {
            get {
                return this.prftupField;
            }
            set {
                this.prftupField = value;
                this.RaisePropertyChanged("Prftup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public decimal Prftdown {
            get {
                return this.prftdownField;
            }
            set {
                this.prftdownField = value;
                this.RaisePropertyChanged("Prftdown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string Email1 {
            get {
                return this.email1Field;
            }
            set {
                this.email1Field = value;
                this.RaisePropertyChanged("Email1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string Email2 {
            get {
                return this.email2Field;
            }
            set {
                this.email2Field = value;
                this.RaisePropertyChanged("Email2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string ExrateCode {
            get {
                return this.exrateCodeField;
            }
            set {
                this.exrateCodeField = value;
                this.RaisePropertyChanged("ExrateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string AcctStatus {
            get {
                return this.acctStatusField;
            }
            set {
                this.acctStatusField = value;
                this.RaisePropertyChanged("AcctStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string StatementAddr1 {
            get {
                return this.statementAddr1Field;
            }
            set {
                this.statementAddr1Field = value;
                this.RaisePropertyChanged("StatementAddr1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string StatementAddr2 {
            get {
                return this.statementAddr2Field;
            }
            set {
                this.statementAddr2Field = value;
                this.RaisePropertyChanged("StatementAddr2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string StatementAddr3 {
            get {
                return this.statementAddr3Field;
            }
            set {
                this.statementAddr3Field = value;
                this.RaisePropertyChanged("StatementAddr3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string StatementAddr4 {
            get {
                return this.statementAddr4Field;
            }
            set {
                this.statementAddr4Field = value;
                this.RaisePropertyChanged("StatementAddr4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string StatementAddr5 {
            get {
                return this.statementAddr5Field;
            }
            set {
                this.statementAddr5Field = value;
                this.RaisePropertyChanged("StatementAddr5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string Internal {
            get {
                return this.internalField;
            }
            set {
                this.internalField = value;
                this.RaisePropertyChanged("Internal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string GemsCode {
            get {
                return this.gemsCodeField;
            }
            set {
                this.gemsCodeField = value;
                this.RaisePropertyChanged("GemsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string GemsCustCode {
            get {
                return this.gemsCustCodeField;
            }
            set {
                this.gemsCustCodeField = value;
                this.RaisePropertyChanged("GemsCustCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string Salesperson {
            get {
                return this.salespersonField;
            }
            set {
                this.salespersonField = value;
                this.RaisePropertyChanged("Salesperson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public decimal Deposit {
            get {
                return this.depositField;
            }
            set {
                this.depositField = value;
                this.RaisePropertyChanged("Deposit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string SalesGroup {
            get {
                return this.salesGroupField;
            }
            set {
                this.salesGroupField = value;
                this.RaisePropertyChanged("SalesGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public System.DateTime Createon {
            get {
                return this.createonField;
            }
            set {
                this.createonField = value;
                this.RaisePropertyChanged("Createon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string Createby {
            get {
                return this.createbyField;
            }
            set {
                this.createbyField = value;
                this.RaisePropertyChanged("Createby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public System.DateTime Updateon {
            get {
                return this.updateonField;
            }
            set {
                this.updateonField = value;
                this.RaisePropertyChanged("Updateon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string Updateby {
            get {
                return this.updatebyField;
            }
            set {
                this.updatebyField = value;
                this.RaisePropertyChanged("Updateby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public System.DateTime SyncOn {
            get {
                return this.syncOnField;
            }
            set {
                this.syncOnField = value;
                this.RaisePropertyChanged("SyncOn");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tbCustomer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class BaseTableOftbCustomer : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tbExrateDetail))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class BaseTableOftbExrateDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tbExrateDetail : BaseTableOftbExrateDetail {
        
        private string companyCodeField;
        
        private string exRateCodeField;
        
        private string rateSeqField;
        
        private string sourceCurrField;
        
        private string targetCurrField;
        
        private System.DateTime periodStartField;
        
        private System.DateTime periodEndField;
        
        private decimal exRateField;
        
        private string operatorField;
        
        private decimal varianceField;
        
        private System.DateTime createOnField;
        
        private string createByField;
        
        private System.DateTime updateOnField;
        
        private string updateByField;
        
        private System.DateTime syncOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExRateCode {
            get {
                return this.exRateCodeField;
            }
            set {
                this.exRateCodeField = value;
                this.RaisePropertyChanged("ExRateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RateSeq {
            get {
                return this.rateSeqField;
            }
            set {
                this.rateSeqField = value;
                this.RaisePropertyChanged("RateSeq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SourceCurr {
            get {
                return this.sourceCurrField;
            }
            set {
                this.sourceCurrField = value;
                this.RaisePropertyChanged("SourceCurr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TargetCurr {
            get {
                return this.targetCurrField;
            }
            set {
                this.targetCurrField = value;
                this.RaisePropertyChanged("TargetCurr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime PeriodStart {
            get {
                return this.periodStartField;
            }
            set {
                this.periodStartField = value;
                this.RaisePropertyChanged("PeriodStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime PeriodEnd {
            get {
                return this.periodEndField;
            }
            set {
                this.periodEndField = value;
                this.RaisePropertyChanged("PeriodEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal ExRate {
            get {
                return this.exRateField;
            }
            set {
                this.exRateField = value;
                this.RaisePropertyChanged("ExRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal Variance {
            get {
                return this.varianceField;
            }
            set {
                this.varianceField = value;
                this.RaisePropertyChanged("Variance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime CreateOn {
            get {
                return this.createOnField;
            }
            set {
                this.createOnField = value;
                this.RaisePropertyChanged("CreateOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CreateBy {
            get {
                return this.createByField;
            }
            set {
                this.createByField = value;
                this.RaisePropertyChanged("CreateBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime UpdateOn {
            get {
                return this.updateOnField;
            }
            set {
                this.updateOnField = value;
                this.RaisePropertyChanged("UpdateOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string UpdateBy {
            get {
                return this.updateByField;
            }
            set {
                this.updateByField = value;
                this.RaisePropertyChanged("UpdateBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime SyncOn {
            get {
                return this.syncOnField;
            }
            set {
                this.syncOnField = value;
                this.RaisePropertyChanged("SyncOn");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface AcctDataSoapChannel : Test.Acct.AcctDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AcctDataSoapClient : System.ServiceModel.ClientBase<Test.Acct.AcctDataSoap>, Test.Acct.AcctDataSoap {
        
        public AcctDataSoapClient() {
        }
        
        public AcctDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AcctDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcctDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcctDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CustomerList(string companyCode, int count) {
            return base.Channel.CustomerList(companyCode, count);
        }
        
        public string UpdateCustomerStatus(string xml) {
            return base.Channel.UpdateCustomerStatus(xml);
        }
        
        public Test.Acct.tbCustomer Demo_Customer() {
            return base.Channel.Demo_Customer();
        }
        
        public string SupplierList(string companyCode, int count) {
            return base.Channel.SupplierList(companyCode, count);
        }
        
        public string UpdateSupplierStatus(string xml) {
            return base.Channel.UpdateSupplierStatus(xml);
        }
        
        public string ExRateDtList(string companyCode, int count) {
            return base.Channel.ExRateDtList(companyCode, count);
        }
        
        public string UpdateExRateDtStatus(string xml) {
            return base.Channel.UpdateExRateDtStatus(xml);
        }
        
        public Test.Acct.tbExrateDetail Demo_ExchangeRate() {
            return base.Channel.Demo_ExchangeRate();
        }
        
        public string CustCrLmtList(string companyCode, int count) {
            return base.Channel.CustCrLmtList(companyCode, count);
        }
        
        public string UpdateCustCrLmtStatus(string xml) {
            return base.Channel.UpdateCustCrLmtStatus(xml);
        }
    }
}
