//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.emp_job_tem {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtEJ_LAST_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_LAST_NUM;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_1;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_2;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_3;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_4;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_5;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_6;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_7;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_8;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_9;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_10;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_11;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_12;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_13;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_14;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_15;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_16;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_17;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_18;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_19;
		protected global::System.Web.UI.WebControls.TextBox txtEJ_JOB_20;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
