//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1873
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.HotelSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcctInvvchResult", Namespace="http://www.hkwtl.com/ad/")]
    [System.SerializableAttribute()]
    public partial class AcctInvvchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocnumField;
        
        private System.DateTime TxndateField;
        
        private System.DateTime LastupdateField;
        
        private System.DateTime CreatedateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.HotelSvc.Invvch InvvchInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Docnum {
            get {
                return this.DocnumField;
            }
            set {
                if ((object.ReferenceEquals(this.DocnumField, value) != true)) {
                    this.DocnumField = value;
                    this.RaisePropertyChanged("Docnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Txndate {
            get {
                return this.TxndateField;
            }
            set {
                if ((this.TxndateField.Equals(value) != true)) {
                    this.TxndateField = value;
                    this.RaisePropertyChanged("Txndate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Lastupdate {
            get {
                return this.LastupdateField;
            }
            set {
                if ((this.LastupdateField.Equals(value) != true)) {
                    this.LastupdateField = value;
                    this.RaisePropertyChanged("Lastupdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Createdate {
            get {
                return this.CreatedateField;
            }
            set {
                if ((this.CreatedateField.Equals(value) != true)) {
                    this.CreatedateField = value;
                    this.RaisePropertyChanged("Createdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Test.HotelSvc.Invvch InvvchInfo {
            get {
                return this.InvvchInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InvvchInfoField, value) != true)) {
                    this.InvvchInfoField = value;
                    this.RaisePropertyChanged("InvvchInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invvch", Namespace="http://www.hkwtl.com/ad/")]
    [System.SerializableAttribute()]
    public partial class Invvch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_BkgrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_SeqnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_StaffcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_TeamcodeField;
        
        private System.DateTime V_PrintdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_VchtypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_VchnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_InvnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_SuppcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_SuppnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_SuppaddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_SupptelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_SuppfaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_HotelcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_HotelnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_HoteladdrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_HoteltelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_HotelfaxField;
        
        private System.DateTime V_ArrivalField;
        
        private System.DateTime V_DepartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_ArrdescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_DepdescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_Remark1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_Remark2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_CfmbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_FormpayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_CostcurrField;
        
        private decimal V_CostamtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_VchrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_Cod1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_Cod2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_ReasoncodeField;
        
        private decimal V_NumofcopyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_RatetypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_RatenameField;
        
        private int V_AdultnumField;
        
        private int V_ChildnumField;
        
        private System.DateTime V_VoiddateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_VoidbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_Void2jbaField;
        
        private decimal V_HkdamtField;
        
        private System.DateTime V_CreateonField;
        
        private System.DateTime V_UpdateonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_PrintbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_PrintteamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_VoidteamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_AgentcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_AgentnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_AgentaddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_AgenttelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_AgentfaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_CrtermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_SellcurrField;
        
        private decimal I_SellamtField;
        
        private decimal I_HkdamtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_Void2jbaField;
        
        private decimal I_NumofcopyField;
        
        private decimal I_TaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_AnalysiscodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_CustrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_ContactpersonField;
        
        private decimal I_PaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_InvtypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_PaydescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_ArpurgerefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string V_ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_OtherrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypecodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TtltaxcurrField;
        
        private decimal TtltaxamtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TtlcommcurrField;
        
        private decimal TtlcommamtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxdescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CosttaxcurrField;
        
        private decimal CosttaxamtField;
        
        private int TaxperField;
        
        private decimal TtlbftaxsellamtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.HotelSvc.Invvchdetail[] InvvchdetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.HotelSvc.Peoinpax[] PeoinpaxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string V_Bkgref {
            get {
                return this.V_BkgrefField;
            }
            set {
                if ((object.ReferenceEquals(this.V_BkgrefField, value) != true)) {
                    this.V_BkgrefField = value;
                    this.RaisePropertyChanged("V_Bkgref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string V_Seqnum {
            get {
                return this.V_SeqnumField;
            }
            set {
                if ((object.ReferenceEquals(this.V_SeqnumField, value) != true)) {
                    this.V_SeqnumField = value;
                    this.RaisePropertyChanged("V_Seqnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string V_Staffcode {
            get {
                return this.V_StaffcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.V_StaffcodeField, value) != true)) {
                    this.V_StaffcodeField = value;
                    this.RaisePropertyChanged("V_Staffcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string V_Teamcode {
            get {
                return this.V_TeamcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.V_TeamcodeField, value) != true)) {
                    this.V_TeamcodeField = value;
                    this.RaisePropertyChanged("V_Teamcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime V_Printdate {
            get {
                return this.V_PrintdateField;
            }
            set {
                if ((this.V_PrintdateField.Equals(value) != true)) {
                    this.V_PrintdateField = value;
                    this.RaisePropertyChanged("V_Printdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string V_Vchtype {
            get {
                return this.V_VchtypeField;
            }
            set {
                if ((object.ReferenceEquals(this.V_VchtypeField, value) != true)) {
                    this.V_VchtypeField = value;
                    this.RaisePropertyChanged("V_Vchtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string V_Vchnum {
            get {
                return this.V_VchnumField;
            }
            set {
                if ((object.ReferenceEquals(this.V_VchnumField, value) != true)) {
                    this.V_VchnumField = value;
                    this.RaisePropertyChanged("V_Vchnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string V_Invnum {
            get {
                return this.V_InvnumField;
            }
            set {
                if ((object.ReferenceEquals(this.V_InvnumField, value) != true)) {
                    this.V_InvnumField = value;
                    this.RaisePropertyChanged("V_Invnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string V_Suppcode {
            get {
                return this.V_SuppcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.V_SuppcodeField, value) != true)) {
                    this.V_SuppcodeField = value;
                    this.RaisePropertyChanged("V_Suppcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string V_Suppname {
            get {
                return this.V_SuppnameField;
            }
            set {
                if ((object.ReferenceEquals(this.V_SuppnameField, value) != true)) {
                    this.V_SuppnameField = value;
                    this.RaisePropertyChanged("V_Suppname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string V_Suppaddr {
            get {
                return this.V_SuppaddrField;
            }
            set {
                if ((object.ReferenceEquals(this.V_SuppaddrField, value) != true)) {
                    this.V_SuppaddrField = value;
                    this.RaisePropertyChanged("V_Suppaddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string V_Supptel {
            get {
                return this.V_SupptelField;
            }
            set {
                if ((object.ReferenceEquals(this.V_SupptelField, value) != true)) {
                    this.V_SupptelField = value;
                    this.RaisePropertyChanged("V_Supptel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string V_Suppfax {
            get {
                return this.V_SuppfaxField;
            }
            set {
                if ((object.ReferenceEquals(this.V_SuppfaxField, value) != true)) {
                    this.V_SuppfaxField = value;
                    this.RaisePropertyChanged("V_Suppfax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string V_Hotelcode {
            get {
                return this.V_HotelcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.V_HotelcodeField, value) != true)) {
                    this.V_HotelcodeField = value;
                    this.RaisePropertyChanged("V_Hotelcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string V_Hotelname {
            get {
                return this.V_HotelnameField;
            }
            set {
                if ((object.ReferenceEquals(this.V_HotelnameField, value) != true)) {
                    this.V_HotelnameField = value;
                    this.RaisePropertyChanged("V_Hotelname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string V_Hoteladdr {
            get {
                return this.V_HoteladdrField;
            }
            set {
                if ((object.ReferenceEquals(this.V_HoteladdrField, value) != true)) {
                    this.V_HoteladdrField = value;
                    this.RaisePropertyChanged("V_Hoteladdr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string V_Hoteltel {
            get {
                return this.V_HoteltelField;
            }
            set {
                if ((object.ReferenceEquals(this.V_HoteltelField, value) != true)) {
                    this.V_HoteltelField = value;
                    this.RaisePropertyChanged("V_Hoteltel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string V_Hotelfax {
            get {
                return this.V_HotelfaxField;
            }
            set {
                if ((object.ReferenceEquals(this.V_HotelfaxField, value) != true)) {
                    this.V_HotelfaxField = value;
                    this.RaisePropertyChanged("V_Hotelfax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.DateTime V_Arrival {
            get {
                return this.V_ArrivalField;
            }
            set {
                if ((this.V_ArrivalField.Equals(value) != true)) {
                    this.V_ArrivalField = value;
                    this.RaisePropertyChanged("V_Arrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.DateTime V_Depart {
            get {
                return this.V_DepartField;
            }
            set {
                if ((this.V_DepartField.Equals(value) != true)) {
                    this.V_DepartField = value;
                    this.RaisePropertyChanged("V_Depart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string V_Arrdesc {
            get {
                return this.V_ArrdescField;
            }
            set {
                if ((object.ReferenceEquals(this.V_ArrdescField, value) != true)) {
                    this.V_ArrdescField = value;
                    this.RaisePropertyChanged("V_Arrdesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string V_Depdesc {
            get {
                return this.V_DepdescField;
            }
            set {
                if ((object.ReferenceEquals(this.V_DepdescField, value) != true)) {
                    this.V_DepdescField = value;
                    this.RaisePropertyChanged("V_Depdesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string V_Remark1 {
            get {
                return this.V_Remark1Field;
            }
            set {
                if ((object.ReferenceEquals(this.V_Remark1Field, value) != true)) {
                    this.V_Remark1Field = value;
                    this.RaisePropertyChanged("V_Remark1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string V_Remark2 {
            get {
                return this.V_Remark2Field;
            }
            set {
                if ((object.ReferenceEquals(this.V_Remark2Field, value) != true)) {
                    this.V_Remark2Field = value;
                    this.RaisePropertyChanged("V_Remark2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string V_Cfmby {
            get {
                return this.V_CfmbyField;
            }
            set {
                if ((object.ReferenceEquals(this.V_CfmbyField, value) != true)) {
                    this.V_CfmbyField = value;
                    this.RaisePropertyChanged("V_Cfmby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string V_Formpay {
            get {
                return this.V_FormpayField;
            }
            set {
                if ((object.ReferenceEquals(this.V_FormpayField, value) != true)) {
                    this.V_FormpayField = value;
                    this.RaisePropertyChanged("V_Formpay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string V_Costcurr {
            get {
                return this.V_CostcurrField;
            }
            set {
                if ((object.ReferenceEquals(this.V_CostcurrField, value) != true)) {
                    this.V_CostcurrField = value;
                    this.RaisePropertyChanged("V_Costcurr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public decimal V_Costamt {
            get {
                return this.V_CostamtField;
            }
            set {
                if ((this.V_CostamtField.Equals(value) != true)) {
                    this.V_CostamtField = value;
                    this.RaisePropertyChanged("V_Costamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string V_Vchref {
            get {
                return this.V_VchrefField;
            }
            set {
                if ((object.ReferenceEquals(this.V_VchrefField, value) != true)) {
                    this.V_VchrefField = value;
                    this.RaisePropertyChanged("V_Vchref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string V_Cod1 {
            get {
                return this.V_Cod1Field;
            }
            set {
                if ((object.ReferenceEquals(this.V_Cod1Field, value) != true)) {
                    this.V_Cod1Field = value;
                    this.RaisePropertyChanged("V_Cod1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string V_Cod2 {
            get {
                return this.V_Cod2Field;
            }
            set {
                if ((object.ReferenceEquals(this.V_Cod2Field, value) != true)) {
                    this.V_Cod2Field = value;
                    this.RaisePropertyChanged("V_Cod2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string V_Reasoncode {
            get {
                return this.V_ReasoncodeField;
            }
            set {
                if ((object.ReferenceEquals(this.V_ReasoncodeField, value) != true)) {
                    this.V_ReasoncodeField = value;
                    this.RaisePropertyChanged("V_Reasoncode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=32)]
        public decimal V_Numofcopy {
            get {
                return this.V_NumofcopyField;
            }
            set {
                if ((this.V_NumofcopyField.Equals(value) != true)) {
                    this.V_NumofcopyField = value;
                    this.RaisePropertyChanged("V_Numofcopy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string V_Ratetype {
            get {
                return this.V_RatetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.V_RatetypeField, value) != true)) {
                    this.V_RatetypeField = value;
                    this.RaisePropertyChanged("V_Ratetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string V_Ratename {
            get {
                return this.V_RatenameField;
            }
            set {
                if ((object.ReferenceEquals(this.V_RatenameField, value) != true)) {
                    this.V_RatenameField = value;
                    this.RaisePropertyChanged("V_Ratename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=35)]
        public int V_Adultnum {
            get {
                return this.V_AdultnumField;
            }
            set {
                if ((this.V_AdultnumField.Equals(value) != true)) {
                    this.V_AdultnumField = value;
                    this.RaisePropertyChanged("V_Adultnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=36)]
        public int V_Childnum {
            get {
                return this.V_ChildnumField;
            }
            set {
                if ((this.V_ChildnumField.Equals(value) != true)) {
                    this.V_ChildnumField = value;
                    this.RaisePropertyChanged("V_Childnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=37)]
        public System.DateTime V_Voiddate {
            get {
                return this.V_VoiddateField;
            }
            set {
                if ((this.V_VoiddateField.Equals(value) != true)) {
                    this.V_VoiddateField = value;
                    this.RaisePropertyChanged("V_Voiddate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string V_Voidby {
            get {
                return this.V_VoidbyField;
            }
            set {
                if ((object.ReferenceEquals(this.V_VoidbyField, value) != true)) {
                    this.V_VoidbyField = value;
                    this.RaisePropertyChanged("V_Voidby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string V_Void2jba {
            get {
                return this.V_Void2jbaField;
            }
            set {
                if ((object.ReferenceEquals(this.V_Void2jbaField, value) != true)) {
                    this.V_Void2jbaField = value;
                    this.RaisePropertyChanged("V_Void2jba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=40)]
        public decimal V_Hkdamt {
            get {
                return this.V_HkdamtField;
            }
            set {
                if ((this.V_HkdamtField.Equals(value) != true)) {
                    this.V_HkdamtField = value;
                    this.RaisePropertyChanged("V_Hkdamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=41)]
        public System.DateTime V_Createon {
            get {
                return this.V_CreateonField;
            }
            set {
                if ((this.V_CreateonField.Equals(value) != true)) {
                    this.V_CreateonField = value;
                    this.RaisePropertyChanged("V_Createon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=42)]
        public System.DateTime V_Updateon {
            get {
                return this.V_UpdateonField;
            }
            set {
                if ((this.V_UpdateonField.Equals(value) != true)) {
                    this.V_UpdateonField = value;
                    this.RaisePropertyChanged("V_Updateon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string V_Printby {
            get {
                return this.V_PrintbyField;
            }
            set {
                if ((object.ReferenceEquals(this.V_PrintbyField, value) != true)) {
                    this.V_PrintbyField = value;
                    this.RaisePropertyChanged("V_Printby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string V_Printteam {
            get {
                return this.V_PrintteamField;
            }
            set {
                if ((object.ReferenceEquals(this.V_PrintteamField, value) != true)) {
                    this.V_PrintteamField = value;
                    this.RaisePropertyChanged("V_Printteam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string V_Voidteam {
            get {
                return this.V_VoidteamField;
            }
            set {
                if ((object.ReferenceEquals(this.V_VoidteamField, value) != true)) {
                    this.V_VoidteamField = value;
                    this.RaisePropertyChanged("V_Voidteam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string I_Agentcode {
            get {
                return this.I_AgentcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.I_AgentcodeField, value) != true)) {
                    this.I_AgentcodeField = value;
                    this.RaisePropertyChanged("I_Agentcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string I_Agentname {
            get {
                return this.I_AgentnameField;
            }
            set {
                if ((object.ReferenceEquals(this.I_AgentnameField, value) != true)) {
                    this.I_AgentnameField = value;
                    this.RaisePropertyChanged("I_Agentname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string I_Agentaddr {
            get {
                return this.I_AgentaddrField;
            }
            set {
                if ((object.ReferenceEquals(this.I_AgentaddrField, value) != true)) {
                    this.I_AgentaddrField = value;
                    this.RaisePropertyChanged("I_Agentaddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=49)]
        public string I_Agenttel {
            get {
                return this.I_AgenttelField;
            }
            set {
                if ((object.ReferenceEquals(this.I_AgenttelField, value) != true)) {
                    this.I_AgenttelField = value;
                    this.RaisePropertyChanged("I_Agenttel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string I_Agentfax {
            get {
                return this.I_AgentfaxField;
            }
            set {
                if ((object.ReferenceEquals(this.I_AgentfaxField, value) != true)) {
                    this.I_AgentfaxField = value;
                    this.RaisePropertyChanged("I_Agentfax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string I_Crterms {
            get {
                return this.I_CrtermsField;
            }
            set {
                if ((object.ReferenceEquals(this.I_CrtermsField, value) != true)) {
                    this.I_CrtermsField = value;
                    this.RaisePropertyChanged("I_Crterms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=52)]
        public string I_Sellcurr {
            get {
                return this.I_SellcurrField;
            }
            set {
                if ((object.ReferenceEquals(this.I_SellcurrField, value) != true)) {
                    this.I_SellcurrField = value;
                    this.RaisePropertyChanged("I_Sellcurr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=53)]
        public decimal I_Sellamt {
            get {
                return this.I_SellamtField;
            }
            set {
                if ((this.I_SellamtField.Equals(value) != true)) {
                    this.I_SellamtField = value;
                    this.RaisePropertyChanged("I_Sellamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=54)]
        public decimal I_Hkdamt {
            get {
                return this.I_HkdamtField;
            }
            set {
                if ((this.I_HkdamtField.Equals(value) != true)) {
                    this.I_HkdamtField = value;
                    this.RaisePropertyChanged("I_Hkdamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=55)]
        public string I_Void2jba {
            get {
                return this.I_Void2jbaField;
            }
            set {
                if ((object.ReferenceEquals(this.I_Void2jbaField, value) != true)) {
                    this.I_Void2jbaField = value;
                    this.RaisePropertyChanged("I_Void2jba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=56)]
        public decimal I_Numofcopy {
            get {
                return this.I_NumofcopyField;
            }
            set {
                if ((this.I_NumofcopyField.Equals(value) != true)) {
                    this.I_NumofcopyField = value;
                    this.RaisePropertyChanged("I_Numofcopy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=57)]
        public decimal I_Tax {
            get {
                return this.I_TaxField;
            }
            set {
                if ((this.I_TaxField.Equals(value) != true)) {
                    this.I_TaxField = value;
                    this.RaisePropertyChanged("I_Tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=58)]
        public string I_Analysiscode {
            get {
                return this.I_AnalysiscodeField;
            }
            set {
                if ((object.ReferenceEquals(this.I_AnalysiscodeField, value) != true)) {
                    this.I_AnalysiscodeField = value;
                    this.RaisePropertyChanged("I_Analysiscode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=59)]
        public string I_Custref {
            get {
                return this.I_CustrefField;
            }
            set {
                if ((object.ReferenceEquals(this.I_CustrefField, value) != true)) {
                    this.I_CustrefField = value;
                    this.RaisePropertyChanged("I_Custref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=60)]
        public string I_Contactperson {
            get {
                return this.I_ContactpersonField;
            }
            set {
                if ((object.ReferenceEquals(this.I_ContactpersonField, value) != true)) {
                    this.I_ContactpersonField = value;
                    this.RaisePropertyChanged("I_Contactperson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=61)]
        public decimal I_Payment {
            get {
                return this.I_PaymentField;
            }
            set {
                if ((this.I_PaymentField.Equals(value) != true)) {
                    this.I_PaymentField = value;
                    this.RaisePropertyChanged("I_Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=62)]
        public string I_Invtype {
            get {
                return this.I_InvtypeField;
            }
            set {
                if ((object.ReferenceEquals(this.I_InvtypeField, value) != true)) {
                    this.I_InvtypeField = value;
                    this.RaisePropertyChanged("I_Invtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=63)]
        public string I_Paydesc {
            get {
                return this.I_PaydescField;
            }
            set {
                if ((object.ReferenceEquals(this.I_PaydescField, value) != true)) {
                    this.I_PaydescField = value;
                    this.RaisePropertyChanged("I_Paydesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=64)]
        public string I_Arpurgeref {
            get {
                return this.I_ArpurgerefField;
            }
            set {
                if ((object.ReferenceEquals(this.I_ArpurgerefField, value) != true)) {
                    this.I_ArpurgerefField = value;
                    this.RaisePropertyChanged("I_Arpurgeref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=65)]
        public string I_Content {
            get {
                return this.I_ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.I_ContentField, value) != true)) {
                    this.I_ContentField = value;
                    this.RaisePropertyChanged("I_Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=66)]
        public string V_Content {
            get {
                return this.V_ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.V_ContentField, value) != true)) {
                    this.V_ContentField = value;
                    this.RaisePropertyChanged("V_Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=67)]
        public string I_Otherref {
            get {
                return this.I_OtherrefField;
            }
            set {
                if ((object.ReferenceEquals(this.I_OtherrefField, value) != true)) {
                    this.I_OtherrefField = value;
                    this.RaisePropertyChanged("I_Otherref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=68)]
        public string Typecode {
            get {
                return this.TypecodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypecodeField, value) != true)) {
                    this.TypecodeField = value;
                    this.RaisePropertyChanged("Typecode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=69)]
        public string Ttltaxcurr {
            get {
                return this.TtltaxcurrField;
            }
            set {
                if ((object.ReferenceEquals(this.TtltaxcurrField, value) != true)) {
                    this.TtltaxcurrField = value;
                    this.RaisePropertyChanged("Ttltaxcurr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=70)]
        public decimal Ttltaxamt {
            get {
                return this.TtltaxamtField;
            }
            set {
                if ((this.TtltaxamtField.Equals(value) != true)) {
                    this.TtltaxamtField = value;
                    this.RaisePropertyChanged("Ttltaxamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=71)]
        public string Ttlcommcurr {
            get {
                return this.TtlcommcurrField;
            }
            set {
                if ((object.ReferenceEquals(this.TtlcommcurrField, value) != true)) {
                    this.TtlcommcurrField = value;
                    this.RaisePropertyChanged("Ttlcommcurr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=72)]
        public decimal Ttlcommamt {
            get {
                return this.TtlcommamtField;
            }
            set {
                if ((this.TtlcommamtField.Equals(value) != true)) {
                    this.TtlcommamtField = value;
                    this.RaisePropertyChanged("Ttlcommamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=73)]
        public string Taxdesc {
            get {
                return this.TaxdescField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxdescField, value) != true)) {
                    this.TaxdescField = value;
                    this.RaisePropertyChanged("Taxdesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=74)]
        public string Costtaxcurr {
            get {
                return this.CosttaxcurrField;
            }
            set {
                if ((object.ReferenceEquals(this.CosttaxcurrField, value) != true)) {
                    this.CosttaxcurrField = value;
                    this.RaisePropertyChanged("Costtaxcurr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=75)]
        public decimal Costtaxamt {
            get {
                return this.CosttaxamtField;
            }
            set {
                if ((this.CosttaxamtField.Equals(value) != true)) {
                    this.CosttaxamtField = value;
                    this.RaisePropertyChanged("Costtaxamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=76)]
        public int Taxper {
            get {
                return this.TaxperField;
            }
            set {
                if ((this.TaxperField.Equals(value) != true)) {
                    this.TaxperField = value;
                    this.RaisePropertyChanged("Taxper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=77)]
        public decimal Ttlbftaxsellamt {
            get {
                return this.TtlbftaxsellamtField;
            }
            set {
                if ((this.TtlbftaxsellamtField.Equals(value) != true)) {
                    this.TtlbftaxsellamtField = value;
                    this.RaisePropertyChanged("Ttlbftaxsellamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=78)]
        public Test.HotelSvc.Invvchdetail[] Invvchdetail {
            get {
                return this.InvvchdetailField;
            }
            set {
                if ((object.ReferenceEquals(this.InvvchdetailField, value) != true)) {
                    this.InvvchdetailField = value;
                    this.RaisePropertyChanged("Invvchdetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=79)]
        public Test.HotelSvc.Peoinpax[] Peoinpax {
            get {
                return this.PeoinpaxField;
            }
            set {
                if ((object.ReferenceEquals(this.PeoinpaxField, value) != true)) {
                    this.PeoinpaxField = value;
                    this.RaisePropertyChanged("Peoinpax");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invvchdetail", Namespace="http://www.hkwtl.com/ad/")]
    [System.SerializableAttribute()]
    public partial class Invvchdetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BkgrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvvchnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeqnumField;
        
        private int RoomsField;
        
        private int NightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServtypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServdescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomtypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmtcurrField;
        
        private decimal AmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcctcurrField;
        
        private decimal AcctamtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailtypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemtypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomcodeField;
        
        private System.DateTime StartdateField;
        
        private System.DateTime EnddateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellcurField;
        
        private decimal TtlsellamtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CostcurField;
        
        private decimal TtlcostamtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypecodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Bkgref {
            get {
                return this.BkgrefField;
            }
            set {
                if ((object.ReferenceEquals(this.BkgrefField, value) != true)) {
                    this.BkgrefField = value;
                    this.RaisePropertyChanged("Bkgref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Segnum {
            get {
                return this.SegnumField;
            }
            set {
                if ((object.ReferenceEquals(this.SegnumField, value) != true)) {
                    this.SegnumField = value;
                    this.RaisePropertyChanged("Segnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Invvchnum {
            get {
                return this.InvvchnumField;
            }
            set {
                if ((object.ReferenceEquals(this.InvvchnumField, value) != true)) {
                    this.InvvchnumField = value;
                    this.RaisePropertyChanged("Invvchnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Seqnum {
            get {
                return this.SeqnumField;
            }
            set {
                if ((object.ReferenceEquals(this.SeqnumField, value) != true)) {
                    this.SeqnumField = value;
                    this.RaisePropertyChanged("Seqnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Rooms {
            get {
                return this.RoomsField;
            }
            set {
                if ((this.RoomsField.Equals(value) != true)) {
                    this.RoomsField = value;
                    this.RaisePropertyChanged("Rooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Night {
            get {
                return this.NightField;
            }
            set {
                if ((this.NightField.Equals(value) != true)) {
                    this.NightField = value;
                    this.RaisePropertyChanged("Night");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Servtype {
            get {
                return this.ServtypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServtypeField, value) != true)) {
                    this.ServtypeField = value;
                    this.RaisePropertyChanged("Servtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Servdesc {
            get {
                return this.ServdescField;
            }
            set {
                if ((object.ReferenceEquals(this.ServdescField, value) != true)) {
                    this.ServdescField = value;
                    this.RaisePropertyChanged("Servdesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Roomtype {
            get {
                return this.RoomtypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomtypeField, value) != true)) {
                    this.RoomtypeField = value;
                    this.RaisePropertyChanged("Roomtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Amtcurr {
            get {
                return this.AmtcurrField;
            }
            set {
                if ((object.ReferenceEquals(this.AmtcurrField, value) != true)) {
                    this.AmtcurrField = value;
                    this.RaisePropertyChanged("Amtcurr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal Amt {
            get {
                return this.AmtField;
            }
            set {
                if ((this.AmtField.Equals(value) != true)) {
                    this.AmtField = value;
                    this.RaisePropertyChanged("Amt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Acctcurr {
            get {
                return this.AcctcurrField;
            }
            set {
                if ((object.ReferenceEquals(this.AcctcurrField, value) != true)) {
                    this.AcctcurrField = value;
                    this.RaisePropertyChanged("Acctcurr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public decimal Acctamt {
            get {
                return this.AcctamtField;
            }
            set {
                if ((this.AcctamtField.Equals(value) != true)) {
                    this.AcctamtField = value;
                    this.RaisePropertyChanged("Acctamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Detailtype {
            get {
                return this.DetailtypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailtypeField, value) != true)) {
                    this.DetailtypeField = value;
                    this.RaisePropertyChanged("Detailtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Itemname {
            get {
                return this.ItemnameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemnameField, value) != true)) {
                    this.ItemnameField = value;
                    this.RaisePropertyChanged("Itemname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Itemtype {
            get {
                return this.ItemtypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemtypeField, value) != true)) {
                    this.ItemtypeField = value;
                    this.RaisePropertyChanged("Itemtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Roomcode {
            get {
                return this.RoomcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomcodeField, value) != true)) {
                    this.RoomcodeField = value;
                    this.RaisePropertyChanged("Roomcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.DateTime Startdate {
            get {
                return this.StartdateField;
            }
            set {
                if ((this.StartdateField.Equals(value) != true)) {
                    this.StartdateField = value;
                    this.RaisePropertyChanged("Startdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.DateTime Enddate {
            get {
                return this.EnddateField;
            }
            set {
                if ((this.EnddateField.Equals(value) != true)) {
                    this.EnddateField = value;
                    this.RaisePropertyChanged("Enddate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Sellcur {
            get {
                return this.SellcurField;
            }
            set {
                if ((object.ReferenceEquals(this.SellcurField, value) != true)) {
                    this.SellcurField = value;
                    this.RaisePropertyChanged("Sellcur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public decimal Ttlsellamt {
            get {
                return this.TtlsellamtField;
            }
            set {
                if ((this.TtlsellamtField.Equals(value) != true)) {
                    this.TtlsellamtField = value;
                    this.RaisePropertyChanged("Ttlsellamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Costcur {
            get {
                return this.CostcurField;
            }
            set {
                if ((object.ReferenceEquals(this.CostcurField, value) != true)) {
                    this.CostcurField = value;
                    this.RaisePropertyChanged("Costcur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public decimal Ttlcostamt {
            get {
                return this.TtlcostamtField;
            }
            set {
                if ((this.TtlcostamtField.Equals(value) != true)) {
                    this.TtlcostamtField = value;
                    this.RaisePropertyChanged("Ttlcostamt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Display {
            get {
                return this.DisplayField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayField, value) != true)) {
                    this.DisplayField = value;
                    this.RaisePropertyChanged("Display");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string Typecode {
            get {
                return this.TypecodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypecodeField, value) != true)) {
                    this.TypecodeField = value;
                    this.RaisePropertyChanged("Typecode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Peoinpax", Namespace="http://www.hkwtl.com/ad/")]
    [System.SerializableAttribute()]
    public partial class Peoinpax : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeqnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaxseqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaxnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Invnum {
            get {
                return this.InvnumField;
            }
            set {
                if ((object.ReferenceEquals(this.InvnumField, value) != true)) {
                    this.InvnumField = value;
                    this.RaisePropertyChanged("Invnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Seqnum {
            get {
                return this.SeqnumField;
            }
            set {
                if ((object.ReferenceEquals(this.SeqnumField, value) != true)) {
                    this.SeqnumField = value;
                    this.RaisePropertyChanged("Seqnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Paxseq {
            get {
                return this.PaxseqField;
            }
            set {
                if ((object.ReferenceEquals(this.PaxseqField, value) != true)) {
                    this.PaxseqField = value;
                    this.RaisePropertyChanged("Paxseq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Paxname {
            get {
                return this.PaxnameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaxnameField, value) != true)) {
                    this.PaxnameField = value;
                    this.RaisePropertyChanged("Paxname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.hkwtl.com/ad/", ConfigurationName="HotelSvc.AccountSyncSoap")]
    public interface AccountSyncSoap {
        
        // CODEGEN: Generating message contract since element name xml from namespace http://www.hkwtl.com/ad/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hkwtl.com/ad/SyncExRate", ReplyAction="*")]
        Test.HotelSvc.SyncExRateResponse SyncExRate(Test.HotelSvc.SyncExRateRequest request);
        
        // CODEGEN: Generating message contract since element name CreateAcctInvvchResultResult from namespace http://www.hkwtl.com/ad/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hkwtl.com/ad/CreateAcctInvvchResult", ReplyAction="*")]
        Test.HotelSvc.CreateAcctInvvchResultResponse CreateAcctInvvchResult(Test.HotelSvc.CreateAcctInvvchResultRequest request);
        
        // CODEGEN: Generating message contract since element name companyCode from namespace http://www.hkwtl.com/ad/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hkwtl.com/ad/GetInvoiceList", ReplyAction="*")]
        Test.HotelSvc.GetInvoiceListResponse GetInvoiceList(Test.HotelSvc.GetInvoiceListRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://www.hkwtl.com/ad/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hkwtl.com/ad/UpdatePeoAcctUpStatus", ReplyAction="*")]
        Test.HotelSvc.UpdatePeoAcctUpStatusResponse UpdatePeoAcctUpStatus(Test.HotelSvc.UpdatePeoAcctUpStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SyncExRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SyncExRate", Namespace="http://www.hkwtl.com/ad/", Order=0)]
        public Test.HotelSvc.SyncExRateRequestBody Body;
        
        public SyncExRateRequest() {
        }
        
        public SyncExRateRequest(Test.HotelSvc.SyncExRateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.hkwtl.com/ad/")]
    public partial class SyncExRateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public SyncExRateRequestBody() {
        }
        
        public SyncExRateRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SyncExRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SyncExRateResponse", Namespace="http://www.hkwtl.com/ad/", Order=0)]
        public Test.HotelSvc.SyncExRateResponseBody Body;
        
        public SyncExRateResponse() {
        }
        
        public SyncExRateResponse(Test.HotelSvc.SyncExRateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.hkwtl.com/ad/")]
    public partial class SyncExRateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SyncExRateResult;
        
        public SyncExRateResponseBody() {
        }
        
        public SyncExRateResponseBody(string SyncExRateResult) {
            this.SyncExRateResult = SyncExRateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAcctInvvchResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAcctInvvchResult", Namespace="http://www.hkwtl.com/ad/", Order=0)]
        public Test.HotelSvc.CreateAcctInvvchResultRequestBody Body;
        
        public CreateAcctInvvchResultRequest() {
        }
        
        public CreateAcctInvvchResultRequest(Test.HotelSvc.CreateAcctInvvchResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateAcctInvvchResultRequestBody {
        
        public CreateAcctInvvchResultRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAcctInvvchResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAcctInvvchResultResponse", Namespace="http://www.hkwtl.com/ad/", Order=0)]
        public Test.HotelSvc.CreateAcctInvvchResultResponseBody Body;
        
        public CreateAcctInvvchResultResponse() {
        }
        
        public CreateAcctInvvchResultResponse(Test.HotelSvc.CreateAcctInvvchResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.hkwtl.com/ad/")]
    public partial class CreateAcctInvvchResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Test.HotelSvc.AcctInvvchResult CreateAcctInvvchResultResult;
        
        public CreateAcctInvvchResultResponseBody() {
        }
        
        public CreateAcctInvvchResultResponseBody(Test.HotelSvc.AcctInvvchResult CreateAcctInvvchResultResult) {
            this.CreateAcctInvvchResultResult = CreateAcctInvvchResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvoiceListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvoiceList", Namespace="http://www.hkwtl.com/ad/", Order=0)]
        public Test.HotelSvc.GetInvoiceListRequestBody Body;
        
        public GetInvoiceListRequest() {
        }
        
        public GetInvoiceListRequest(Test.HotelSvc.GetInvoiceListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.hkwtl.com/ad/")]
    public partial class GetInvoiceListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string companyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime lastDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int count;
        
        public GetInvoiceListRequestBody() {
        }
        
        public GetInvoiceListRequestBody(string companyCode, System.DateTime lastDate, int count) {
            this.companyCode = companyCode;
            this.lastDate = lastDate;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvoiceListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvoiceListResponse", Namespace="http://www.hkwtl.com/ad/", Order=0)]
        public Test.HotelSvc.GetInvoiceListResponseBody Body;
        
        public GetInvoiceListResponse() {
        }
        
        public GetInvoiceListResponse(Test.HotelSvc.GetInvoiceListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.hkwtl.com/ad/")]
    public partial class GetInvoiceListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInvoiceListResult;
        
        public GetInvoiceListResponseBody() {
        }
        
        public GetInvoiceListResponseBody(string GetInvoiceListResult) {
            this.GetInvoiceListResult = GetInvoiceListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePeoAcctUpStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePeoAcctUpStatus", Namespace="http://www.hkwtl.com/ad/", Order=0)]
        public Test.HotelSvc.UpdatePeoAcctUpStatusRequestBody Body;
        
        public UpdatePeoAcctUpStatusRequest() {
        }
        
        public UpdatePeoAcctUpStatusRequest(Test.HotelSvc.UpdatePeoAcctUpStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.hkwtl.com/ad/")]
    public partial class UpdatePeoAcctUpStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public UpdatePeoAcctUpStatusRequestBody() {
        }
        
        public UpdatePeoAcctUpStatusRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePeoAcctUpStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePeoAcctUpStatusResponse", Namespace="http://www.hkwtl.com/ad/", Order=0)]
        public Test.HotelSvc.UpdatePeoAcctUpStatusResponseBody Body;
        
        public UpdatePeoAcctUpStatusResponse() {
        }
        
        public UpdatePeoAcctUpStatusResponse(Test.HotelSvc.UpdatePeoAcctUpStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.hkwtl.com/ad/")]
    public partial class UpdatePeoAcctUpStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdatePeoAcctUpStatusResult;
        
        public UpdatePeoAcctUpStatusResponseBody() {
        }
        
        public UpdatePeoAcctUpStatusResponseBody(string UpdatePeoAcctUpStatusResult) {
            this.UpdatePeoAcctUpStatusResult = UpdatePeoAcctUpStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface AccountSyncSoapChannel : Test.HotelSvc.AccountSyncSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AccountSyncSoapClient : System.ServiceModel.ClientBase<Test.HotelSvc.AccountSyncSoap>, Test.HotelSvc.AccountSyncSoap {
        
        public AccountSyncSoapClient() {
        }
        
        public AccountSyncSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountSyncSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountSyncSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountSyncSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.HotelSvc.SyncExRateResponse Test.HotelSvc.AccountSyncSoap.SyncExRate(Test.HotelSvc.SyncExRateRequest request) {
            return base.Channel.SyncExRate(request);
        }
        
        public string SyncExRate(string xml) {
            Test.HotelSvc.SyncExRateRequest inValue = new Test.HotelSvc.SyncExRateRequest();
            inValue.Body = new Test.HotelSvc.SyncExRateRequestBody();
            inValue.Body.xml = xml;
            Test.HotelSvc.SyncExRateResponse retVal = ((Test.HotelSvc.AccountSyncSoap)(this)).SyncExRate(inValue);
            return retVal.Body.SyncExRateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.HotelSvc.CreateAcctInvvchResultResponse Test.HotelSvc.AccountSyncSoap.CreateAcctInvvchResult(Test.HotelSvc.CreateAcctInvvchResultRequest request) {
            return base.Channel.CreateAcctInvvchResult(request);
        }
        
        public Test.HotelSvc.AcctInvvchResult CreateAcctInvvchResult() {
            Test.HotelSvc.CreateAcctInvvchResultRequest inValue = new Test.HotelSvc.CreateAcctInvvchResultRequest();
            inValue.Body = new Test.HotelSvc.CreateAcctInvvchResultRequestBody();
            Test.HotelSvc.CreateAcctInvvchResultResponse retVal = ((Test.HotelSvc.AccountSyncSoap)(this)).CreateAcctInvvchResult(inValue);
            return retVal.Body.CreateAcctInvvchResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.HotelSvc.GetInvoiceListResponse Test.HotelSvc.AccountSyncSoap.GetInvoiceList(Test.HotelSvc.GetInvoiceListRequest request) {
            return base.Channel.GetInvoiceList(request);
        }
        
        public string GetInvoiceList(string companyCode, System.DateTime lastDate, int count) {
            Test.HotelSvc.GetInvoiceListRequest inValue = new Test.HotelSvc.GetInvoiceListRequest();
            inValue.Body = new Test.HotelSvc.GetInvoiceListRequestBody();
            inValue.Body.companyCode = companyCode;
            inValue.Body.lastDate = lastDate;
            inValue.Body.count = count;
            Test.HotelSvc.GetInvoiceListResponse retVal = ((Test.HotelSvc.AccountSyncSoap)(this)).GetInvoiceList(inValue);
            return retVal.Body.GetInvoiceListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.HotelSvc.UpdatePeoAcctUpStatusResponse Test.HotelSvc.AccountSyncSoap.UpdatePeoAcctUpStatus(Test.HotelSvc.UpdatePeoAcctUpStatusRequest request) {
            return base.Channel.UpdatePeoAcctUpStatus(request);
        }
        
        public string UpdatePeoAcctUpStatus(string xml) {
            Test.HotelSvc.UpdatePeoAcctUpStatusRequest inValue = new Test.HotelSvc.UpdatePeoAcctUpStatusRequest();
            inValue.Body = new Test.HotelSvc.UpdatePeoAcctUpStatusRequestBody();
            inValue.Body.xml = xml;
            Test.HotelSvc.UpdatePeoAcctUpStatusResponse retVal = ((Test.HotelSvc.AccountSyncSoap)(this)).UpdatePeoAcctUpStatus(inValue);
            return retVal.Body.UpdatePeoAcctUpStatusResult;
        }
    }
}
