//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.holiday_date {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblHO_CO_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtHO_LOC;
	protected global::System.Web.UI.WebControls.Label lblHO_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtHO_DATE_START;
		protected global::System.Web.UI.WebControls.TextBox txtHO_DATE_END;
		protected global::System.Web.UI.WebControls.TextBox txtHO_DESC;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
