//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.servicetype {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblST_CO_CODE;
	protected global::System.Web.UI.WebControls.Label lblST_JOB_CODE;
	protected global::System.Web.UI.WebControls.Label lblST_SER_CODE;
	protected global::System.Web.UI.WebControls.Label lblST_DESC;
	protected global::System.Web.UI.WebControls.Label lblST_DESC1;
	protected global::System.Web.UI.WebControls.Label lblST_DESC_T1;
	protected global::System.Web.UI.WebControls.Label lblST_DESC_S1;
	protected global::System.Web.UI.WebControls.Label lblST_DESC_T2;
	protected global::System.Web.UI.WebControls.Label lblST_DESC_S2;

    }
}
