//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.non_hist {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCO_CODE;
	protected global::System.Web.UI.WebControls.Label lblSTAFF_CODE;
	protected global::System.Web.UI.WebControls.Label lblDATE;
	protected global::System.Web.UI.WebControls.Label lblTYPE;
	protected global::System.Web.UI.WebControls.Label lblANNUAL;
	protected global::System.Web.UI.WebControls.Label lblSICK;
	protected global::System.Web.UI.WebControls.Label lblADMIN;
	protected global::System.Web.UI.WebControls.Label lblOT_PAY;

    }
}
