//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.jobbud {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblJOB_CO_CODE;
	protected global::System.Web.UI.WebControls.Label lblJOB_CODE;
	protected global::System.Web.UI.WebControls.Label lblJOB_SER;
	protected global::System.Web.UI.WebControls.Label lblJOB_POS;
	protected global::System.Web.UI.WebControls.Label lblJOB_STAFF;
	protected global::System.Web.UI.WebControls.Label lblJOB_BUD;
	protected global::System.Web.UI.WebControls.Label lblJOB_NOR;
	protected global::System.Web.UI.WebControls.Label lblJOB_NOR_EXP;
	protected global::System.Web.UI.WebControls.Label lblJOB_OT;
	protected global::System.Web.UI.WebControls.Label lblJOB_OT_EXP;

    }
}
