//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.temp_all_app {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtTEM_CO_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_STAFF_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_WORK_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_LINE_NO;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_HOUR_TYPE;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_APP_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_SER_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_JOB_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_BF_SUM;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_NOR_HOUR_0;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_NOR_HOUR_1;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_NOR_HOUR_2;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_NOR_HOUR_3;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_NOR_HOUR_4;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_NOR_HOUR_5;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_NOR_HOUR_6;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_TYPE;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_APP_FLAG;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_QUE;
		protected global::System.Web.UI.WebControls.TextBox txtTEM_POS_CODE;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
