//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.temp_all_app {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblTEM_CO_CODE;
	protected global::System.Web.UI.WebControls.Label lblTEM_STAFF_CODE;
	protected global::System.Web.UI.WebControls.Label lblTEM_WORK_DATE;
	protected global::System.Web.UI.WebControls.Label lblTEM_LINE_NO;
	protected global::System.Web.UI.WebControls.Label lblTEM_HOUR_TYPE;
	protected global::System.Web.UI.WebControls.Label lblTEM_APP_CODE;
	protected global::System.Web.UI.WebControls.Label lblTEM_SER_CODE;
	protected global::System.Web.UI.WebControls.Label lblTEM_JOB_CODE;
	protected global::System.Web.UI.WebControls.Label lblTEM_BF_SUM;
	protected global::System.Web.UI.WebControls.Label lblTEM_NOR_HOUR_0;
	protected global::System.Web.UI.WebControls.Label lblTEM_NOR_HOUR_1;
	protected global::System.Web.UI.WebControls.Label lblTEM_NOR_HOUR_2;
	protected global::System.Web.UI.WebControls.Label lblTEM_NOR_HOUR_3;
	protected global::System.Web.UI.WebControls.Label lblTEM_NOR_HOUR_4;
	protected global::System.Web.UI.WebControls.Label lblTEM_NOR_HOUR_5;
	protected global::System.Web.UI.WebControls.Label lblTEM_NOR_HOUR_6;
	protected global::System.Web.UI.WebControls.Label lblTEM_TYPE;
	protected global::System.Web.UI.WebControls.Label lblTEM_APP_FLAG;
	protected global::System.Web.UI.WebControls.Label lblTEM_QUE;
	protected global::System.Web.UI.WebControls.Label lblTEM_POS_CODE;

    }
}
