//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.plan_pos {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblPLA_POS_CO;
	protected global::System.Web.UI.WebControls.Label lblPLA_POS_OFF;
	protected global::System.Web.UI.WebControls.Label lblPLA_POS_CODE;
	protected global::System.Web.UI.WebControls.Label lblPLA_POS_NUM;
	protected global::System.Web.UI.WebControls.Label lblPLA_POS_NOR;
	protected global::System.Web.UI.WebControls.Label lblPLA_POS_OT1;
	protected global::System.Web.UI.WebControls.Label lblPLA_POS_OT2;
	protected global::System.Web.UI.WebControls.Label lblPLA_POS_OT3;
	protected global::System.Web.UI.WebControls.Label lblPLA_POS_T1;
	protected global::System.Web.UI.WebControls.Label lblPLA_POS_T2;
	protected global::System.Web.UI.WebControls.Label lblPLA_POS_T3;

    }
}
