//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WongTung.Web.bk_jobbud {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblJOB_CO_CODE;
	protected global::System.Web.UI.WebControls.Label lblJOB_CODE;
	protected global::System.Web.UI.WebControls.Label lblJOB_SER;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_POS;
	protected global::System.Web.UI.WebControls.Label lblJOB_STAFF;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_BUD;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_NOR;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_NOR_EXP;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_OT;
		protected global::System.Web.UI.WebControls.TextBox txtJOB_OT_EXP;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
